// 世界各国列表
export const COUNTRIES = [
  // 亚洲
  { value: 'china', label: '中国' },
  { value: 'japan', label: '日本' },
  { value: 'korea', label: '韩国' },
  { value: 'singapore', label: '新加坡' },
  { value: 'thailand', label: '泰国' },
  { value: 'vietnam', label: '越南' },
  { value: 'malaysia', label: '马来西亚' },
  { value: 'indonesia', label: '印度尼西亚' },
  { value: 'philippines', label: '菲律宾' },
  { value: 'india', label: '印度' },
  { value: 'pakistan', label: '巴基斯坦' },
  { value: 'bangladesh', label: '孟加拉国' },
  { value: 'sri_lanka', label: '斯里兰卡' },
  { value: 'myanmar', label: '缅甸' },
  { value: 'cambodia', label: '柬埔寨' },
  { value: 'laos', label: '老挝' },
  { value: 'brunei', label: '文莱' },
  { value: 'mongolia', label: '蒙古' },
  { value: 'north_korea', label: '朝鲜' },
  { value: 'taiwan', label: '台湾' },
  { value: 'hong_kong', label: '香港' },
  { value: 'macau', label: '澳门' },
  { value: 'nepal', label: '尼泊尔' },
  { value: 'bhutan', label: '不丹' },
  { value: 'maldives', label: '马尔代夫' },
  { value: 'afghanistan', label: '阿富汗' },
  { value: 'iran', label: '伊朗' },
  { value: 'iraq', label: '伊拉克' },
  { value: 'saudi_arabia', label: '沙特阿拉伯' },
  { value: 'uae', label: '阿联酋' },
  { value: 'qatar', label: '卡塔尔' },
  { value: 'kuwait', label: '科威特' },
  { value: 'bahrain', label: '巴林' },
  { value: 'oman', label: '阿曼' },
  { value: 'yemen', label: '也门' },
  { value: 'jordan', label: '约旦' },
  { value: 'lebanon', label: '黎巴嫩' },
  { value: 'syria', label: '叙利亚' },
  { value: 'israel', label: '以色列' },
  { value: 'palestine', label: '巴勒斯坦' },
  { value: 'turkey', label: '土耳其' },
  { value: 'cyprus', label: '塞浦路斯' },
  { value: 'armenia', label: '亚美尼亚' },
  { value: 'azerbaijan', label: '阿塞拜疆' },
  { value: 'georgia', label: '格鲁吉亚' },
  { value: 'kazakhstan', label: '哈萨克斯坦' },
  { value: 'uzbekistan', label: '乌兹别克斯坦' },
  { value: 'turkmenistan', label: '土库曼斯坦' },
  { value: 'kyrgyzstan', label: '吉尔吉斯斯坦' },
  { value: 'tajikistan', label: '塔吉克斯坦' },

  // 欧洲
  { value: 'uk', label: '英国' },
  { value: 'germany', label: '德国' },
  { value: 'france', label: '法国' },
  { value: 'italy', label: '意大利' },
  { value: 'spain', label: '西班牙' },
  { value: 'portugal', label: '葡萄牙' },
  { value: 'netherlands', label: '荷兰' },
  { value: 'belgium', label: '比利时' },
  { value: 'luxembourg', label: '卢森堡' },
  { value: 'switzerland', label: '瑞士' },
  { value: 'austria', label: '奥地利' },
  { value: 'poland', label: '波兰' },
  { value: 'czech_republic', label: '捷克' },
  { value: 'slovakia', label: '斯洛伐克' },
  { value: 'hungary', label: '匈牙利' },
  { value: 'romania', label: '罗马尼亚' },
  { value: 'bulgaria', label: '保加利亚' },
  { value: 'greece', label: '希腊' },
  { value: 'albania', label: '阿尔巴尼亚' },
  { value: 'macedonia', label: '北马其顿' },
  { value: 'montenegro', label: '黑山' },
  { value: 'serbia', label: '塞尔维亚' },
  { value: 'bosnia_herzegovina', label: '波黑' },
  { value: 'croatia', label: '克罗地亚' },
  { value: 'slovenia', label: '斯洛文尼亚' },
  { value: 'russia', label: '俄罗斯' },
  { value: 'ukraine', label: '乌克兰' },
  { value: 'belarus', label: '白俄罗斯' },
  { value: 'moldova', label: '摩尔多瓦' },
  { value: 'lithuania', label: '立陶宛' },
  { value: 'latvia', label: '拉脱维亚' },
  { value: 'estonia', label: '爱沙尼亚' },
  { value: 'finland', label: '芬兰' },
  { value: 'sweden', label: '瑞典' },
  { value: 'norway', label: '挪威' },
  { value: 'denmark', label: '丹麦' },
  { value: 'iceland', label: '冰岛' },
  { value: 'ireland', label: '爱尔兰' },
  { value: 'malta', label: '马耳他' },
  { value: 'monaco', label: '摩纳哥' },
  { value: 'andorra', label: '安道尔' },
  { value: 'san_marino', label: '圣马力诺' },
  { value: 'vatican', label: '梵蒂冈' },
  { value: 'liechtenstein', label: '列支敦士登' },

  // 北美洲
  { value: 'usa', label: '美国' },
  { value: 'canada', label: '加拿大' },
  { value: 'mexico', label: '墨西哥' },
  { value: 'guatemala', label: '危地马拉' },
  { value: 'belize', label: '伯利兹' },
  { value: 'el_salvador', label: '萨尔瓦多' },
  { value: 'honduras', label: '洪都拉斯' },
  { value: 'nicaragua', label: '尼加拉瓜' },
  { value: 'costa_rica', label: '哥斯达黎加' },
  { value: 'panama', label: '巴拿马' },
  { value: 'cuba', label: '古巴' },
  { value: 'jamaica', label: '牙买加' },
  { value: 'haiti', label: '海地' },
  { value: 'dominican_republic', label: '多米尼加' },
  { value: 'bahamas', label: '巴哈马' },
  { value: 'barbados', label: '巴巴多斯' },
  { value: 'trinidad_tobago', label: '特立尼达和多巴哥' },

  // 南美洲
  { value: 'brazil', label: '巴西' },
  { value: 'argentina', label: '阿根廷' },
  { value: 'chile', label: '智利' },
  { value: 'peru', label: '秘鲁' },
  { value: 'colombia', label: '哥伦比亚' },
  { value: 'venezuela', label: '委内瑞拉' },
  { value: 'ecuador', label: '厄瓜多尔' },
  { value: 'bolivia', label: '玻利维亚' },
  { value: 'paraguay', label: '巴拉圭' },
  { value: 'uruguay', label: '乌拉圭' },
  { value: 'guyana', label: '圭亚那' },
  { value: 'suriname', label: '苏里南' },

  // 大洋洲
  { value: 'australia', label: '澳大利亚' },
  { value: 'new_zealand', label: '新西兰' },
  { value: 'fiji', label: '斐济' },
  { value: 'papua_new_guinea', label: '巴布亚新几内亚' },
  { value: 'samoa', label: '萨摩亚' },
  { value: 'tonga', label: '汤加' },
  { value: 'vanuatu', label: '瓦努阿图' },
  { value: 'solomon_islands', label: '所罗门群岛' },
  { value: 'palau', label: '帕劳' },
  { value: 'micronesia', label: '密克罗尼西亚' },
  { value: 'marshall_islands', label: '马绍尔群岛' },
  { value: 'kiribati', label: '基里巴斯' },
  { value: 'nauru', label: '瑙鲁' },
  { value: 'tuvalu', label: '图瓦卢' },

  // 非洲
  { value: 'south_africa', label: '南非' },
  { value: 'egypt', label: '埃及' },
  { value: 'nigeria', label: '尼日利亚' },
  { value: 'kenya', label: '肯尼亚' },
  { value: 'ethiopia', label: '埃塞俄比亚' },
  { value: 'ghana', label: '加纳' },
  { value: 'morocco', label: '摩洛哥' },
  { value: 'algeria', label: '阿尔及利亚' },
  { value: 'tunisia', label: '突尼斯' },
  { value: 'libya', label: '利比亚' },
  { value: 'sudan', label: '苏丹' },
  { value: 'south_sudan', label: '南苏丹' },
  { value: 'chad', label: '乍得' },
  { value: 'niger', label: '尼日尔' },
  { value: 'mali', label: '马里' },
  { value: 'burkina_faso', label: '布基纳法索' },
  { value: 'senegal', label: '塞内加尔' },
  { value: 'guinea', label: '几内亚' },
  { value: 'sierra_leone', label: '塞拉利昂' },
  { value: 'liberia', label: '利比里亚' },
  { value: 'ivory_coast', label: '科特迪瓦' },
  { value: 'togo', label: '多哥' },
  { value: 'benin', label: '贝宁' },
  { value: 'cameroon', label: '喀麦隆' },
  { value: 'central_african_republic', label: '中非共和国' },
  { value: 'equatorial_guinea', label: '赤道几内亚' },
  { value: 'gabon', label: '加蓬' },
  { value: 'congo', label: '刚果共和国' },
  { value: 'drc', label: '刚果民主共和国' },
  { value: 'angola', label: '安哥拉' },
  { value: 'zambia', label: '赞比亚' },
  { value: 'zimbabwe', label: '津巴布韦' },
  { value: 'botswana', label: '博茨瓦纳' },
  { value: 'namibia', label: '纳米比亚' },
  { value: 'lesotho', label: '莱索托' },
  { value: 'swaziland', label: '斯威士兰' },
  { value: 'mozambique', label: '莫桑比克' },
  { value: 'malawi', label: '马拉维' },
  { value: 'tanzania', label: '坦桑尼亚' },
  { value: 'uganda', label: '乌干达' },
  { value: 'rwanda', label: '卢旺达' },
  { value: 'burundi', label: '布隆迪' },
  { value: 'somalia', label: '索马里' },
  { value: 'djibouti', label: '吉布提' },
  { value: 'eritrea', label: '厄立特里亚' },
  { value: 'madagascar', label: '马达加斯加' },
  { value: 'mauritius', label: '毛里求斯' },
  { value: 'seychelles', label: '塞舌尔' },
  { value: 'comoros', label: '科摩罗' },
  { value: 'cape_verde', label: '佛得角' },
  { value: 'sao_tome_principe', label: '圣多美和普林西比' },
  { value: 'gambia', label: '冈比亚' },
  { value: 'guinea_bissau', label: '几内亚比绍' }
];

// 按地区分组的国家列表
export const COUNTRIES_BY_REGION = {
  asia: COUNTRIES.filter(country => [
    'china', 'japan', 'korea', 'singapore', 'thailand', 'vietnam', 'malaysia', 'indonesia',
    'philippines', 'india', 'pakistan', 'bangladesh', 'sri_lanka', 'myanmar', 'cambodia',
    'laos', 'brunei', 'mongolia', 'north_korea', 'taiwan', 'hong_kong', 'macau',
    'nepal', 'bhutan', 'maldives', 'afghanistan', 'iran', 'iraq', 'saudi_arabia',
    'uae', 'qatar', 'kuwait', 'bahrain', 'oman', 'yemen', 'jordan', 'lebanon',
    'syria', 'israel', 'palestine', 'turkey', 'cyprus', 'armenia', 'azerbaijan',
    'georgia', 'kazakhstan', 'uzbekistan', 'turkmenistan', 'kyrgyzstan', 'tajikistan'
  ].includes(country.value)),

  europe: COUNTRIES.filter(country => [
    'uk', 'germany', 'france', 'italy', 'spain', 'portugal', 'netherlands', 'belgium',
    'luxembourg', 'switzerland', 'austria', 'poland', 'czech_republic', 'slovakia',
    'hungary', 'romania', 'bulgaria', 'greece', 'albania', 'macedonia', 'montenegro',
    'serbia', 'bosnia_herzegovina', 'croatia', 'slovenia', 'russia', 'ukraine',
    'belarus', 'moldova', 'lithuania', 'latvia', 'estonia', 'finland', 'sweden',
    'norway', 'denmark', 'iceland', 'ireland', 'malta', 'monaco', 'andorra',
    'san_marino', 'vatican', 'liechtenstein'
  ].includes(country.value)),

  north_america: COUNTRIES.filter(country => [
    'usa', 'canada', 'mexico', 'guatemala', 'belize', 'el_salvador', 'honduras',
    'nicaragua', 'costa_rica', 'panama', 'cuba', 'jamaica', 'haiti', 'dominican_republic',
    'bahamas', 'barbados', 'trinidad_tobago'
  ].includes(country.value)),

  south_america: COUNTRIES.filter(country => [
    'brazil', 'argentina', 'chile', 'peru', 'colombia', 'venezuela', 'ecuador',
    'bolivia', 'paraguay', 'uruguay', 'guyana', 'suriname'
  ].includes(country.value)),

  oceania: COUNTRIES.filter(country => [
    'australia', 'new_zealand', 'fiji', 'papua_new_guinea', 'samoa', 'tonga',
    'vanuatu', 'solomon_islands', 'palau', 'micronesia', 'marshall_islands',
    'kiribati', 'nauru', 'tuvalu'
  ].includes(country.value)),

  africa: COUNTRIES.filter(country => [
    'south_africa', 'egypt', 'nigeria', 'kenya', 'ethiopia', 'ghana', 'morocco',
    'algeria', 'tunisia', 'libya', 'sudan', 'south_sudan', 'chad', 'niger',
    'mali', 'burkina_faso', 'senegal', 'guinea', 'sierra_leone', 'liberia',
    'ivory_coast', 'togo', 'benin', 'cameroon', 'central_african_republic',
    'equatorial_guinea', 'gabon', 'congo', 'drc', 'angola', 'zambia',
    'zimbabwe', 'botswana', 'namibia', 'lesotho', 'swaziland', 'mozambique',
    'malawi', 'tanzania', 'uganda', 'rwanda', 'burundi', 'somalia',
    'djibouti', 'eritrea', 'madagascar', 'mauritius', 'seychelles',
    'comoros', 'cape_verde', 'sao_tome_principe', 'gambia', 'guinea_bissau'
  ].includes(country.value))
};

// 常用国家列表（原有的10个国家）
export const POPULAR_COUNTRIES = [
  { value: 'china', label: '中国' },
  { value: 'usa', label: '美国' },
  { value: 'uk', label: '英国' },
  { value: 'japan', label: '日本' },
  { value: 'korea', label: '韩国' },
  { value: 'germany', label: '德国' },
  { value: 'france', label: '法国' },
  { value: 'canada', label: '加拿大' },
  { value: 'australia', label: '澳大利亚' },
  { value: 'singapore', label: '新加坡' }
];