// 10 种最常用语言
export type CountryLang = 'zh' | 'en' | 'es' | 'fr' | 'de' | 'ru' | 'ja' | 'ko' | 'ar' | 'pt';

export const COUNTRY_LANG_OPTIONS: { value: CountryLang; label: string }[] = [
  { value: 'zh', label: '中文' },
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Español' },
  { value: 'fr', label: 'Français' },
  { value: 'de', label: 'Deutsch' },
  { value: 'ru', label: 'Русский' },
  { value: 'ja', label: '日本語' },
  { value: 'ko', label: '한국어' },
  { value: 'ar', label: 'العربية' },
  { value: 'pt', label: 'Português' },
];

// 20 个热门国家（可随业务再调）
export const HOT_COUNTRIES: Record<CountryLang, { value: string; label: string }[]> = {
  zh: [
    { value: 'CN', label: '中国' },
    { value: 'US', label: '美国' },
    { value: 'JP', label: '日本' },
    { value: 'KR', label: '韩国' },
    { value: 'SG', label: '新加坡' },
    { value: 'CA', label: '加拿大' },
    { value: 'AU', label: '澳大利亚' },
    { value: 'GB', label: '英国' },
    { value: 'FR', label: '法国' },
    { value: 'DE', label: '德国' },
    { value: 'IT', label: '意大利' },
    { value: 'ES', label: '西班牙' },
    { value: 'RU', label: '俄罗斯' },
    { value: 'BR', label: '巴西' },
    { value: 'MX', label: '墨西哥' },
    { value: 'IN', label: '印度' },
    { value: 'TH', label: '泰国' },
    { value: 'MY', label: '马来西亚' },
    { value: 'NL', label: '荷兰' },
    { value: 'SE', label: '瑞典' },
  ],
  en: [
    { value: 'CN', label: 'China' },
    { value: 'US', label: 'United States' },
    { value: 'JP', label: 'Japan' },
    { value: 'KR', label: 'South Korea' },
    { value: 'SG', label: 'Singapore' },
    { value: 'CA', label: 'Canada' },
    { value: 'AU', label: 'Australia' },
    { value: 'GB', label: 'United Kingdom' },
    { value: 'FR', label: 'France' },
    { value: 'DE', label: 'Germany' },
    { value: 'IT', label: 'Italy' },
    { value: 'ES', label: 'Spain' },
    { value: 'RU', label: 'Russia' },
    { value: 'BR', label: 'Brazil' },
    { value: 'MX', label: 'Mexico' },
    { value: 'IN', label: 'India' },
    { value: 'TH', label: 'Thailand' },
    { value: 'MY', label: 'Malaysia' },
    { value: 'NL', label: 'Netherlands' },
    { value: 'SE', label: 'Sweden' },
  ],
  es: [
    { value: 'CN', label: 'China' },
    { value: 'US', label: 'Estados Unidos' },
    { value: 'JP', label: 'Japón' },
    { value: 'KR', label: 'Corea del Sur' },
    { value: 'SG', label: 'Singapur' },
    { value: 'CA', label: 'Canadá' },
    { value: 'AU', label: 'Australia' },
    { value: 'GB', label: 'Reino Unido' },
    { value: 'FR', label: 'Francia' },
    { value: 'DE', label: 'Alemania' },
    { value: 'IT', label: 'Italia' },
    { value: 'ES', label: 'España' },
    { value: 'RU', label: 'Rusia' },
    { value: 'BR', label: 'Brasil' },
    { value: 'MX', label: 'México' },
    { value: 'IN', label: 'India' },
    { value: 'TH', label: 'Tailandia' },
    { value: 'MY', label: 'Malasia' },
    { value: 'NL', label: 'Países Bajos' },
    { value: 'SE', label: 'Suecia' },
  ],
  fr: [
    { value: 'CN', label: 'Chine' },
    { value: 'US', label: 'États-Unis' },
    { value: 'JP', label: 'Japon' },
    { value: 'KR', label: 'Corée du Sud' },
    { value: 'SG', label: 'Singapour' },
    { value: 'CA', label: 'Canada' },
    { value: 'AU', label: 'Australie' },
    { value: 'GB', label: 'Royaume-Uni' },
    { value: 'FR', label: 'France' },
    { value: 'DE', label: 'Allemagne' },
    { value: 'IT', label: 'Italie' },
    { value: 'ES', label: 'Espagne' },
    { value: 'RU', label: 'Russie' },
    { value: 'BR', label: 'Brésil' },
    { value: 'MX', label: 'Mexique' },
    { value: 'IN', label: 'Inde' },
    { value: 'TH', label: 'Thaïlande' },
    { value: 'MY', label: 'Malaisie' },
    { value: 'NL', label: 'Pays-Bas' },
    { value: 'SE', label: 'Suède' },
  ],
  de: [
    { value: 'CN', label: 'China' },
    { value: 'US', label: 'Vereinigte Staaten' },
    { value: 'JP', label: 'Japan' },
    { value: 'KR', label: 'Südkorea' },
    { value: 'SG', label: 'Singapur' },
    { value: 'CA', label: 'Kanada' },
    { value: 'AU', label: 'Australien' },
    { value: 'GB', label: 'Vereinigtes Königreich' },
    { value: 'FR', label: 'Frankreich' },
    { value: 'DE', label: 'Deutschland' },
    { value: 'IT', label: 'Italien' },
    { value: 'ES', label: 'Spanien' },
    { value: 'RU', label: 'Russland' },
    { value: 'BR', label: 'Brasilien' },
    { value: 'MX', label: 'Mexiko' },
    { value: 'IN', label: 'Indien' },
    { value: 'TH', label: 'Thailand' },
    { value: 'MY', label: 'Malaysia' },
    { value: 'NL', label: 'Niederlande' },
    { value: 'SE', label: 'Schweden' },
  ],
  ru: [
    { value: 'CN', label: 'Китай' },
    { value: 'US', label: 'США' },
    { value: 'JP', label: 'Япония' },
    { value: 'KR', label: 'Южная Корея' },
    { value: 'SG', label: 'Сингапур' },
    { value: 'CA', label: 'Канада' },
    { value: 'AU', label: 'Австралия' },
    { value: 'GB', label: 'Великобритания' },
    { value: 'FR', label: 'Франция' },
    { value: 'DE', label: 'Германия' },
    { value: 'IT', label: 'Италия' },
    { value: 'ES', label: 'Испания' },
    { value: 'RU', label: 'Россия' },
    { value: 'BR', label: 'Бразилия' },
    { value: 'MX', label: 'Мексика' },
    { value: 'IN', label: 'Индия' },
    { value: 'TH', label: 'Таиланд' },
    { value: 'MY', label: 'Малайзия' },
    { value: 'NL', label: 'Нидерланды' },
    { value: 'SE', label: 'Швеция' },
  ],
  ja: [
    { value: 'CN', label: '中国' },
    { value: 'US', label: 'アメリカ合衆国' },
    { value: 'JP', label: '日本' },
    { value: 'KR', label: '韓国' },
    { value: 'SG', label: 'シンガポール' },
    { value: 'CA', label: 'カナダ' },
    { value: 'AU', label: 'オーストラリア' },
    { value: 'GB', label: 'イギリス' },
    { value: 'FR', label: 'フランス' },
    { value: 'DE', label: 'ドイツ' },
    { value: 'IT', label: 'イタリア' },
    { value: 'ES', label: 'スペイン' },
    { value: 'RU', label: 'ロシア' },
    { value: 'BR', label: 'ブラジル' },
    { value: 'MX', label: 'メキシコ' },
    { value: 'IN', label: 'インド' },
    { value: 'TH', label: 'タイ' },
    { value: 'MY', label: 'マレーシア' },
    { value: 'NL', label: 'オランダ' },
    { value: 'SE', label: 'スウェーデン' },
  ],
  ko: [
    { value: 'CN', label: '중국' },
    { value: 'US', label: '미국' },
    { value: 'JP', label: '일본' },
    { value: 'KR', label: '한국' },
    { value: 'SG', label: '싱가포르' },
    { value: 'CA', label: '캐나다' },
    { value: 'AU', label: '호주' },
    { value: 'GB', label: '영국' },
    { value: 'FR', label: '프랑스' },
    { value: 'DE', label: '독일' },
    { value: 'IT', label: '이탈리아' },
    { value: 'ES', label: '스페인' },
    { value: 'RU', label: '러시아' },
    { value: 'BR', label: '브라질' },
    { value: 'MX', label: '멕시코' },
    { value: 'IN', label: '인도' },
    { value: 'TH', label: '태국' },
    { value: 'MY', label: '말레이시아' },
    { value: 'NL', label: '네덜란드' },
    { value: 'SE', label: '스웨덴' },
  ],
  ar: [
    { value: 'CN', label: 'الصين' },
    { value: 'US', label: 'الولايات المتحدة' },
    { value: 'JP', label: 'اليابان' },
    { value: 'KR', label: 'كوريا الجنوبية' },
    { value: 'SG', label: 'سنغافورة' },
    { value: 'CA', label: 'كندا' },
    { value: 'AU', label: 'أستراليا' },
    { value: 'GB', label: 'المملكة المتحدة' },
    { value: 'FR', label: 'فرنسا' },
    { value: 'DE', label: 'ألمانيا' },
    { value: 'IT', label: 'إيطاليا' },
    { value: 'ES', label: 'إسبانيا' },
    { value: 'RU', label: 'روسيا' },
    { value: 'BR', label: 'البرازيل' },
    { value: 'MX', label: 'المكسيك' },
    { value: 'IN', label: 'الهند' },
    { value: 'TH', label: 'تايلاند' },
    { value: 'MY', label: 'ماليزيا' },
    { value: 'NL', label: 'هولندا' },
    { value: 'SE', label: 'السويد' },
  ],
  pt: [
    { value: 'CN', label: 'China' },
    { value: 'US', label: 'Estados Unidos' },
    { value: 'JP', label: 'Japão' },
    { value: 'KR', label: 'Coreia do Sul' },
    { value: 'SG', label: 'Singapura' },
    { value: 'CA', label: 'Canadá' },
    { value: 'AU', label: 'Austrália' },
    { value: 'GB', label: 'Reino Unido' },
    { value: 'FR', label: 'França' },
    { value: 'DE', label: 'Alemanha' },
    { value: 'IT', label: 'Itália' },
    { value: 'ES', label: 'Espanha' },
    { value: 'RU', label: 'Rússia' },
    { value: 'BR', label: 'Brasil' },
    { value: 'MX', label: 'México' },
    { value: 'IN', label: 'Índia' },
    { value: 'TH', label: 'Tailândia' },
    { value: 'MY', label: 'Malásia' },
    { value: 'NL', label: 'Países Baixos' },
    { value: 'SE', label: 'Suécia' },
  ],
};

// 默认语言为中文
export const DEFAULT_COUNTRY_LANG: CountryLang = 'zh';